---

- name: create {{ webserver_hostname }} under /var/www/site directory
  command: mkdir -p /var/www/site/{{ webserver_hostname }}
  sudo: true
  tags:
    - createsite

- name: add vhosts configuration to sites-available folder
  template: src=apache2_vhosts.j2 dest=/etc/apache2/sites-available/{{ webserver_hostname }}.conf
  sudo: true
  notify:
    - restart apache2
  tags:
    - createsite

- name: enable {{ webserver_hostname }} site
  command: a2ensite {{ webserver_hostname }} creates=/etc/apache2/sites-enabled/{{ webserver_hostname }}.conf
  sudo: true
  notify:
    - restart apache2
  tags:
    - createsite
