---
# Apache2 ssl
- name: apache_ssl | enable ssl module
  command: a2enmod ssl creates=/etc/apache2/mods-enabled/ssl.conf
  sudo: true
  notify:
    - restart apache2
  tags:
    - createsite

- name: apache_ssl | add vhosts for ssl version
  template: src=apache2_vhosts-ssl.j2 dest=/etc/apache2/sites-available/{{ webserver_hostname }}-ssl.conf
  sudo: true
  notify:
    - restart apache2
  tags:
    - createsite

- name: apache_ssl | enable ssl site
  command: a2ensite {{ webserver_hostname }}-ssl creates=/etc/apache2/sites-enabled/{{ webserver_hostname }}-ssl.conf
  sudo: true
  notify:
    - restart apache2
  tags:
    - createsite
