---
# file: composer.yml

# Install composer globally

- name: get composer and install
  shell: curl -sS https://getcomposer.org/installer | php creates=/usr/local/bin/composer
  sudo: true
  tags:
    - drupal

- name: rename composer.phar to composer
  shell: mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  sudo: true
  tags:
    - drupal
