---
# Ansible apt usage: http://docs.ansible.com/apt_module.html 

# PHP installation
- name: install php packages
  apt: pkg=php5 state=latest update_cache=yes
  with_items:
    - php5
    - php-cli
    - php5-common
    - php5-dev
    - php5-gd
    - php5-mysql
    - php5-xmlrpc
    - php5-curl
    - php5-mcrypt
    - php-soap
    - php-apc
    - php-pear
  sudo: true 
  notify:
    - restart apache2
