---
# Base operations before proceed configuration

- apt: update_cache=yes
  sudo: true

- name: set permissions to /tmp directory
  file: path=/tmp mode=0777 recurse=yes
  sudo: true 

- name: install curl
  apt: name=curl state=latest 
  sudo: true
  tags:
    - curl

- name: install git
  apt: name=git state=latest
  sudo: true
  tags:
    - git

- name: create ssl certificates
  shell: openssl req -new -nodes -x509 -subj "/C=CN/ST=Zhejiang/L=Ningbo/O=IT/CN={{ ansible_fqdn }}" -days 3650 -keyout /etc/ssl/private/server.key -out /etc/ssl/certs/server.crt -extensions v3_ca creates=/etc/ssl/certs/server.crt
  sudo: true
  tags:
    - ssl
